declare module "ace/mode/python" {}
declare module "ace/mode/javascript" {}
declare module "ace/mode/typescript" {}
declare module "ace/mode/java" {}
declare module "ace/mode/c_cpp" {}
declare module "ace/mode/rust" {}
declare module "ace/mode/golang" {}
declare module "ace/theme/monokai" {}
declare module "ace/theme/github" {}
declare module "ace/theme/dracula" {}
declare module "ace/theme/tomorrow_night" {}
declare module "ace/theme/solarized_dark" {}
declare module "ace/ext/language_tools" {}
